---
layout: post
title:  "Players"
date:   2021-06-21 20:30:00 -0400
categories: players
---
* Guild Of Unreliable Adventurers
** Jimmy
*** Background
Jimmy grew up with a step father and a mother and three sisters in the town of
Hundlestone. His step father and sisters where forest gnomes.
*** Family
**** Step Father: Tozu
The step father was a small time arms dealer. He was imposter as a cheese vendor for the Lord's Alliance. When
the coast was clear he would smuggle posionous common items in and out of
respective barracks.

Overtime he started moving into exotic animals. Over the course of a few months
he recieved many threats. He discounted these threats because the business was
doing very well and he was able to save enough money to send Jimmy away to
Neverwinter Academy, hoping he could get Gayvin to love him as much as she loved Jimmy.

Within a few days of Jimmy being sent to Neverwinter Academy Tozu's house was
raided by an array of beassts from giant wolverines, raptors,
griffons, dragon wrymlins and pteranodon.

Tried as he and Jimmy and he could they failed to protect Gaywin from being taken.
**** Mother: Gayvin
Is very loving rock gnome women. She had three daughters at 230 and her youngest son at the age of 350 with
her husband Lanlen. Lanlen was drafted into the Lord's Alliance. After a few
year's stopped hearing from Lanlen and decided to raise Jimmy on her own.

Gaywin eventaully met Tozu and they married. They lived together for 40 years
until Jimmy was going to Academy of Neverwinter.
**** Sisters : Juniper, Cedar, Magnolia
His three sisters range between 80 to 120 years older then Jimmy. By the time
Jimmy was born the youngest daughter was on her way to college. Jimmy knows very
little about Juniper and Cedar. Gayvin has mentioned some success Juniper as a wizard.
*** Events
- The Timbers are married
- Sisters are born
- Jimmy is born
- Lanlen is drafted to the military
- Gaywin remarries
- Tozu smuggles up to exotic animals
- Jimmy's home is raided and mother is kidnapped
- Jimmy goes to Neverwinter Academy
- Conjuration school is a front for Necromancy and so Jimmy leaves
- Jimmy adventure starts in the Under Dark
*** Goals
Become powerful to inact these contigencies. Ordered by preference
1. Aquire access to a powerful spell to undo his misfortunues (e.g. loss of
   father and mother). Specfics are flexible.
2. Find and save his mother
3. Ruin his mother's captures

Overall Jimmy is a nice guy. He will resort to unfavorable means if it means the
furtherment of his goals.

** Dodge
- Description: a front liner who has fell the most
- Relationship: Friends
- Met in the Underkdark
- Alignment: Chaotic Neutral
- Class: Barbarian/Wizard
- Attunements
	- Bracers of Ogre Power
	- Headband of Intellect
** Fisher
- Description: Likes the morning lord
** Dames
Druid
** Forfax
Morals
- Do not sell evil staff to children
- Do not lightening bolt politicians to vote them out of office.
- Do run recklessly into battle and smash the first thing you see

* Inactive
** Callibern
Shapecahnger Warlock
** Hames
- Player: James
- Class: Cleric
- Status: Death by snu snu
- Notes: He didn't talk much.
** Twitch
- Player: Oscar
- Didn't talk much
- Status: Pissed off
- Dodge found his name was Twitch
